version: '3'

networks:
  lan:

services:

  reverseproxy:
    image: reverseproxy
    container_name: reverseproxy
    restart: always
    ports:
        - 8080:8080
        - 8081:8081
        - 8082:8082

  core1:
    depends_on:
      - reverseproxy
    image: neo4j:3.3.1-enterprise
    container_name: core1
    networks:
      - lan
    ports:
      - 7474:7474
      - 6477:6477
      - 7687:7687
    volumes:
      - /storage/nfs/neo4j-${HOSTNAME}/neo4j-core1/conf:/conf
      - /storage/nfs/neo4j-${HOSTNAME}/neo4j-core1/data:/data
      - /storage/nfs/neo4j-${HOSTNAME}/neo4j-core1/logs:/logs
      - /storage/nfs/neo4j-${HOSTNAME}/neo4j-core1/plugins:/plugins
    environment:
#      - NEO4J_AUTH=none
      - NEO4J_AUTH=neo4j/${PASSWORD}
      - NEO4J_dbms_mode=CORE
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes      
      - NEO4J_causalClustering_expectedCoreClusterSize=3
      - NEO4J_causalClustering_initialDiscoveryMembers=core1:5000,core2:5000,core3:5000
      - NEO4J_dbms_connector_http_listen__address=:7474
      - NEO4J_dbms_connector_https_listen__address=:6477
      - NEO4J_dbms_connector_bolt_listen__address=:7687
      - NEO4J_dbms_security_allow__csv__import__from__file__urls=true
      - NEO4J_dbms_memory_heap_max__size=20480M

  core2:
    depends_on:
      - reverseproxy
    image: neo4j:3.3.1-enterprise
    container_name: core2
    networks:
      - lan
    ports:
      - 7475:7475
      - 6478:6478
      - 7688:7688
    volumes:
      - /storage/nfs/neo4j-${HOSTNAME}/neo4j-core2/conf:/conf
      - /storage/nfs/neo4j-${HOSTNAME}/neo4j-core2/data:/data
      - /storage/nfs/neo4j-${HOSTNAME}/neo4j-core2/logs:/logs
      - /storage/nfs/neo4j-${HOSTNAME}/neo4j-core1/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/${PASSWORD}
      - NEO4J_dbms_mode=CORE
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_causalClustering_expectedCoreClusterSize=3
      - NEO4J_causalClustering_initialDiscoveryMembers=core1:5000,core2:5000,core3:5000
      - NEO4J_dbms_connector_http_listen__address=:7475
      - NEO4J_dbms_connector_https_listen__address=:6478
      - NEO4J_dbms_connector_bolt_listen__address=:7688
      - NEO4J_dbms_security_allow__csv__import__from__file__urls=true
      - NEO4J_dbms_memory_heap_max__size=20480M
      
  core3:
    depends_on:
      - reverseproxy
    image: neo4j:3.3.1-enterprise
    container_name: core3
    networks:
      - lan
    ports:
      - 7476:7476
      - 6479:6479
      - 7689:7689
    volumes:
      - /storage/nfs/neo4j-${HOSTNAME}/neo4j-core3/conf:/conf
      - /storage/nfs/neo4j-${HOSTNAME}/neo4j-core3/data:/data
      - /storage/nfs/neo4j-${HOSTNAME}/neo4j-core3/logs:/logs
      - /storage/nfs/neo4j-${HOSTNAME}/neo4j-core1/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/${PASSWORD}
      - NEO4J_dbms_mode=CORE
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_causalClustering_expectedCoreClusterSize=3
      - NEO4J_causalClustering_initialDiscoveryMembers=core1:5000,core2:5000,core3:5000
      - NEO4J_dbms_connector_http_listen__address=:7476
      - NEO4J_dbms_connector_https_listen__address=:6479
      - NEO4J_dbms_connector_bolt_listen__address=:7689
      - NEO4J_dbms_security_allow__csv__import__from__file__urls=true
      - NEO4J_dbms_memory_heap_max__size=20480M

